### ISSUE TITLE
DC1/DC2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi-adapter-template#2]
всё-таки DC1 идут красиво на j1

к j2 кажется оба DC никак не относятся, DC2 у нас будет вести в никуда

![image](https://github.com/rusefi/uaefi-adapter-template/assets/48498823/603f8149-2e62-4423-961d-38a6c2776025)

**Comment by Nadezhda-n** [comment]
@rusefillc 
![image](https://github.com/rusefi/uaefi-adapter-template/assets/99179773/4887ea10-11c7-44da-b245-ee5d899bbd12)
